# Namespace where the application will be deployed
namespace: "sock-shop"

serviceAccount:
  create: true
  name: "nginx-ingress-serviceaccount"

global:
    registry: ''


istio:
    enabled: false

java:
    options: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom

carts:
    image:
        repo: 715841363614.dkr.ecr.eu-west-1.amazonaws.com/sock-shop-carts:latest
        tag: 0.4.8
    containerPort: 80
    resources:
        limits:
            cpu: 300m
            memory: 2000Mi
        requests:
            cpu: 300m
            memory: 2000Mi
cartsdb:
    image:
        repo: mongo
        tag: 4.4.0
    resources:
        requests:
            cpu: 500m
            memory: 512Mi
        limits:
            cpu: 500m
            memory: 512Mi
    persistentVolume:
        storageClass: ''
        size: 512Mi

zipkin:
    image:
        repo: openzipkin/zipkin
        tag: 2.21
    resources:
        limits:
            cpu: 300m
            memory: 1000Mi
        requests:
            cpu: 100m
            memory: 300Mi
    enabled:  false
    url: zipkin.zipkin.svc.cluster.local
#alb:
#  # Tags to associate with the Application Load Balancer
#  tags: "Name=alb-name"
#
#ingress:
#  # Subnets for the ingress controller
#  subnets: "subnet-12345678,subnet-23456789"
#  # ACM certificate ARN for HTTPS
#  certificateArn: "arn:aws:acm:us-west-2:123456789012:certificate/abcd1234-5678-90ab-cdef-1234567890ab"
#  # Hostname for the ingress controller
#  host: "petclinic.example.com"

